version: "3.1"
services:

  # mysql:
  #   image: mysql:8.0.18
  #   command: --default-authentication-plugin=mysql_native_password
  #   container_name: api-mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: task99
  #     MYSQL_DATABASE: supplystore
  #     MYSQL_USER: api
  #     MYSQL_PASSWORD: api
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - api-network  
  db:
    image: mysql:5.7
    container_name: api-mysql
    environment:
      MYSQL_ROOT_PASSWORD: task99
      MYSQL_DATABASE: supplystore
      MYSQL_USER: api
      MYSQL_PASSWORD: api
    ports:
      - "3306:3306"
    networks:
      - api-network  

  webserver:
    image: nginx:alpine
    container_name: api-webserver
    working_dir: /application
    volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - //var/run/docker.sock:/tmp/docker.sock
    environment:
      - VIRTUAL_HOST=host.docker.internal
    ports:
      - "8080:80"
    expose: 
      - "9000"
    networks:
      - api-network

  php-fpm:
    build: phpdocker/php-fpm
    container_name: api-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    environment:
        XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1  
    networks:
      - api-network  

networks: 
    api-network:
      driver: bridge