
security_login:
    path: /security/login    
    controller: App\Controller\Security\SecurityController::login
    methods:
        - POST
security_register:
    path: /security/register
    controller: App\Controller\Security\SecurityController::register
    methods:
        - POST
