# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    access_denied_listener:
        json: true
    allowed_methods_listener: true
    routing_loader:
        default_format: json
        include_format: false
    view:
        default_engine: json
        view_response_listener: 'force'
    format_listener: 
        rules:
            - {path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - {path: ^/security, prefer_extension: true, fallback_format: json, priorities: [ json ] }